<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xmlns:transitions="http://www.bonitasoft.org/ns/studio/process/decision/transitions" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision http://www.bonitasoft.org/ns/studio/process/decision/transitions http://www.bonitasoft.org/ns/studio/process#//decision/transitions">
  <process:MainProcess xmi:id="_TYPMYBEDEeyrCJnFey_Gig" name="Diagrama_CreacionDeSociedadesAnonimas" author="monofri" bonitaVersion="7.12.1" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_TYPzcBEDEeyrCJnFey_Gig" name="Creación de sociedades anónimas" displayName="Creación de sociedades anónimas">
      <elements xmi:type="process:Lane" xmi:id="_eCUD4BM8EeysRqMPSB8vQg" name="Mesa de Entradas" actor="_-yHoUBNEEeysRqMPSB8vQg">
        <elements xmi:type="process:XORGateway" xmi:id="_kuuzMBMpEeyD6LYpCyY8Nw" documentation="Determina si la información ingresada por el apoderado en el registro de sociedad anónima es valida" name="¿La infomación es válida?" outgoing="_xV3S0BMpEeyD6LYpCyY8Nw _x6tsUBMpEeyD6LYpCyY8Nw" incoming="_iYBagBMpEeyD6LYpCyY8Nw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_iX3pghMpEeyD6LYpCyY8Nw" name="¿La infomación es válida?" content="¿La infomación es válida?" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_iX3pgRMpEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_iX3pgxMpEeyD6LYpCyY8Nw" name="Determina si la información ingresada por el apoderado en el registro de sociedad anónima es valida" content="Determina si la información ingresada por el apoderado en el registro de sociedad anónima es valida" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_x6qpABMpEeyD6LYpCyY8Nw" name="Generar número de expediente y enviar mail al apoderado" outgoing="_iCLMIB73Eeyh5_OLYVEXkQ" incoming="_x6tsUBMpEeyD6LYpCyY8Nw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_x6qpAhMpEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_x6qpARMpEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_x6qpAxMpEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_x6qpBBMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_x6qpBRMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_x6qpBhMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_x6qpCBMpEeyD6LYpCyY8Nw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_x6qpBxMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_nYTWIBMsEeyD6LYpCyY8Nw" name="Enviar mail al apoderado informando trámite incorrecto y plazo de correción" outgoing="_C7drcB76Eeyh5_OLYVEXkQ" incoming="_xV3S0BMpEeyD6LYpCyY8Nw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xVv-ERMpEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xVv-EBMpEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xVv-EhMpEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xVv-ExMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xVv-FBMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xVv-FRMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xVv-FxMpEeyD6LYpCyY8Nw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xVv-FhMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_BgoScBNEEeysRqMPSB8vQg" name="Generar carpetas" outgoing="_08c9cB76Eeyh5_OLYVEXkQ" incoming="_3WaecB76Eeyh5_OLYVEXkQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BgoSchNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BgoScRNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BgoScxNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_BgoSdBNEEeysRqMPSB8vQg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_BgoSdRNEEeysRqMPSB8vQg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_BgoSdhNEEeysRqMPSB8vQg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_BgoSeBNEEeysRqMPSB8vQg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_BgoSdxNEEeysRqMPSB8vQg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Bgo5gRNEEeysRqMPSB8vQg">
            <targetForm xmi:type="expression:Expression" xmi:id="_Bgo5ghNEEeysRqMPSB8vQg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Bgo5gBNEEeysRqMPSB8vQg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Bgo5gxNEEeysRqMPSB8vQg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_tQ188BPTEeyD6LYpCyY8Nw" name="Enviar mail al apoderado informando trámite finalizado" outgoing="_zdRC8BPTEeyD6LYpCyY8Nw" incoming="_08c9cB76Eeyh5_OLYVEXkQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_tQ188hPTEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_tQ188RPTEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_tQ188xPTEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_tQ189BPTEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_tQ189RPTEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_tQ189hPTEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_tQ18-BPTEeyD6LYpCyY8Nw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_tQ189xPTEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_xCblMBW1Eey3K_c3c_D4pg" name="Validar información ingresada" outgoing="_iYBagBMpEeyD6LYpCyY8Nw" incoming="_LE6gYBMpEeyD6LYpCyY8Nw _EzbSoB76Eeyh5_OLYVEXkQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_LEqBsBMpEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_LEpaoBMpEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_LEqBsRMpEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_LEqBshMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_LEqBsxMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_LEqBtBMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_LEqBthMpEeyD6LYpCyY8Nw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_LEqBtRMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_xCcMQhW1Eey3K_c3c_D4pg">
            <targetForm xmi:type="expression:Expression" xmi:id="_xCcMQxW1Eey3K_c3c_D4pg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_xCcMQRW1Eey3K_c3c_D4pg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_xCcMRBW1Eey3K_c3c_D4pg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_C7aBEB76Eeyh5_OLYVEXkQ" name="Timer plazo de correción" outgoing="_EzbSoB76Eeyh5_OLYVEXkQ" incoming="_C7drcB76Eeyh5_OLYVEXkQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_C7aoIR76Eeyh5_OLYVEXkQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_C7aoIB76Eeyh5_OLYVEXkQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_C7aoIh76Eeyh5_OLYVEXkQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_TYPzcREDEeyrCJnFey_Gig" documentation="Apoderado de la sociedad anónima" name="Apoderado" actor="_TYPzihEDEeyrCJnFey_Gig">
        <elements xmi:type="process:StartEvent" xmi:id="_TYPzchEDEeyrCJnFey_Gig" name="Registro de sociedad anónima" outgoing="_TYPzhxEDEeyrCJnFey_Gig">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TYPzcxEDEeyrCJnFey_Gig" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TYPzdBEDEeyrCJnFey_Gig" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TYPzdREDEeyrCJnFey_Gig" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_TYPzdhEDEeyrCJnFey_Gig" name="Registrar información de sociedad anónima" outgoing="_LE6gYBMpEeyD6LYpCyY8Nw" incoming="_TYPzhxEDEeyrCJnFey_Gig" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TYPzdxEDEeyrCJnFey_Gig" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TYPzeBEDEeyrCJnFey_Gig" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TYPzeREDEeyrCJnFey_Gig" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_TYPzehEDEeyrCJnFey_Gig" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_TYPzexEDEeyrCJnFey_Gig" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_TYPzfBEDEeyrCJnFey_Gig" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_TYPzfREDEeyrCJnFey_Gig" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_TYPzfhEDEeyrCJnFey_Gig" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_TYPzfxEDEeyrCJnFey_Gig">
            <targetForm xmi:type="expression:Expression" xmi:id="_TYPzgBEDEeyrCJnFey_Gig" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_TYPzgREDEeyrCJnFey_Gig"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_TYPzghEDEeyrCJnFey_Gig" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_0CtSUBPTEeyD6LYpCyY8Nw" name="Retiro de documentación" outgoing="_2uaqoBPTEeyD6LYpCyY8Nw" incoming="_zdRC8BPTEeyD6LYpCyY8Nw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_zdP00BPTEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_zdPNwRPTEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_zdP00RPTEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_zdP00hPTEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_zdP00xPTEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_zdP01BPTEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_zdP01hPTEeyD6LYpCyY8Nw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_zdP01RPTEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_0CtSWhPTEeyD6LYpCyY8Nw">
            <targetForm xmi:type="expression:Expression" xmi:id="_0CtSWxPTEeyD6LYpCyY8Nw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_0CtSWRPTEeyD6LYpCyY8Nw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_0CtSXBPTEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_XL3P0BNEEeysRqMPSB8vQg" name="Fin trámite" incoming="_2uaqoBPTEeyD6LYpCyY8Nw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XL3P0hNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XL3P0RNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XL3P0xNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <filters xmi:type="process:ActorFilter" xmi:id="_FI200BMtEeyD6LYpCyY8Nw" name="Apoderado" definitionId="bonita-actorfilter-initiator" definitionVersion="1.0">
          <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_FI200RMtEeyD6LYpCyY8Nw" definitionId="bonita-actorfilter-initiator" version="1.0">
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_FI200hMtEeyD6LYpCyY8Nw" key="autoAssign">
              <expression xmi:type="expression:Expression" xmi:id="_FI200xMtEeyD6LYpCyY8Nw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </parameters>
          </configuration>
        </filters>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_wX-ZIBMnEeyD6LYpCyY8Nw" name="Area de legales" actor="_maOu4BMtEeyD6LYpCyY8Nw">
        <elements xmi:type="process:Task" xmi:id="_eLcIgBMtEeyD6LYpCyY8Nw" name="Evaluar estatuto" outgoing="_-bYlUBMuEeyD6LYpCyY8Nw" incoming="_iCLMIB73Eeyh5_OLYVEXkQ _1mXSkB75Eeyh5_OLYVEXkQ" actor="_maOu4BMtEeyD6LYpCyY8Nw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dSgVYRMtEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dSgVYBMtEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dSgVYhMtEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dSgVYxMtEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dSgVZBMtEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dSgVZRMtEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dSgVZxMtEeyD6LYpCyY8Nw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dSgVZhMtEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_2NHeQBTtEey3K_c3c_D4pg" name="7 días" outgoing="_x_dUYBdFEeypj_zk8mSC2g">
            <condition xmi:type="expression:Expression" xmi:id="_mBS5QBdFEeypj_zk8mSC2g" name="7 días: 00:00:00" content="604800000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_eLdWoRMtEeyD6LYpCyY8Nw">
            <targetForm xmi:type="expression:Expression" xmi:id="_eLdWohMtEeyD6LYpCyY8Nw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_eLdWoBMtEeyD6LYpCyY8Nw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_eLdWoxMtEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_-_3ycBMuEeyD6LYpCyY8Nw" name="¿Trámite válido?" outgoing="_K1ZO8BMvEeyD6LYpCyY8Nw _NbGs8BMvEeyD6LYpCyY8Nw" incoming="_-bYlUBMuEeyD6LYpCyY8Nw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-bU68RMuEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-bU68BMuEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-bU68hMuEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_NbDpoBMvEeyD6LYpCyY8Nw" name="Enviar email de trámite inválido al apoderado con los cambios sugeridos" outgoing="_0Hp44B75Eeyh5_OLYVEXkQ" incoming="_NbGs8BMvEeyD6LYpCyY8Nw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_NbEQsRMvEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_NbEQsBMvEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_NbEQshMvEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_NbEQsxMvEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_NbEQtBMvEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_NbEQtRMvEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_NbEQtxMvEeyD6LYpCyY8Nw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_NbEQthMvEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_lQDI0BMvEeyD6LYpCyY8Nw" name="Realizar estampillado y Generar QR" outgoing="_3WaecB76Eeyh5_OLYVEXkQ" incoming="_K1ZO8BMvEeyD6LYpCyY8Nw _x_dUYBdFEeypj_zk8mSC2g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_lQDI0hMvEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_lQDI0RMvEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_lQDI0xMvEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_lQDI1BMvEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_lQDI1RMvEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_lQDI1hMvEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_lQDI2BMvEeyD6LYpCyY8Nw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_lQDI1xMvEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_0G-jcB75Eeyh5_OLYVEXkQ" name="Timer para corrección" outgoing="_1mXSkB75Eeyh5_OLYVEXkQ" incoming="_0Hp44B75Eeyh5_OLYVEXkQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0HhWAR75Eeyh5_OLYVEXkQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0HhWAB75Eeyh5_OLYVEXkQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0HhWAh75Eeyh5_OLYVEXkQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_TYPzgxEDEeyrCJnFey_Gig">
        <targetForm xmi:type="expression:Expression" xmi:id="_TYPzhBEDEeyrCJnFey_Gig" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_TYPzhREDEeyrCJnFey_Gig">
        <targetForm xmi:type="expression:Expression" xmi:id="_TYPzhhEDEeyrCJnFey_Gig" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_TYPzhxEDEeyrCJnFey_Gig" target="_TYPzdhEDEeyrCJnFey_Gig" source="_TYPzchEDEeyrCJnFey_Gig">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_TYPziBEDEeyrCJnFey_Gig"/>
        <condition xmi:type="expression:Expression" xmi:id="_TYPziREDEeyrCJnFey_Gig" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_LE6gYBMpEeyD6LYpCyY8Nw" target="_xCblMBW1Eey3K_c3c_D4pg" source="_TYPzdhEDEeyrCJnFey_Gig">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_LE7HcBMpEeyD6LYpCyY8Nw"/>
        <condition xmi:type="expression:Expression" xmi:id="_LE7HcRMpEeyD6LYpCyY8Nw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_iYBagBMpEeyD6LYpCyY8Nw" target="_kuuzMBMpEeyD6LYpCyY8Nw" source="_xCblMBW1Eey3K_c3c_D4pg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_iYBagRMpEeyD6LYpCyY8Nw"/>
        <condition xmi:type="expression:Expression" xmi:id="_iYCBkBMpEeyD6LYpCyY8Nw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xV3S0BMpEeyD6LYpCyY8Nw" name="No" target="_nYTWIBMsEeyD6LYpCyY8Nw" source="_kuuzMBMpEeyD6LYpCyY8Nw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_W7VfUBMqEeyD6LYpCyY8Nw">
          <defaultAction xmi:type="transitions:TakeTransitionAction" xmi:id="_W7WGYBMqEeyD6LYpCyY8Nw"/>
        </decisionTable>
        <condition xmi:type="expression:Expression" xmi:id="_xV5IARMpEeyD6LYpCyY8Nw" name="0 == 0" content="0 == 0" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_x6tsUBMpEeyD6LYpCyY8Nw" name="Si" target="_x6qpABMpEeyD6LYpCyY8Nw" source="_kuuzMBMpEeyD6LYpCyY8Nw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_x6u6cBMpEeyD6LYpCyY8Nw"/>
        <condition xmi:type="expression:Expression" xmi:id="_x6u6cRMpEeyD6LYpCyY8Nw" name="0 == 1" content="0 == 1" interpreter="GROOVY" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-bYlUBMuEeyD6LYpCyY8Nw" target="_-_3ycBMuEeyD6LYpCyY8Nw" source="_eLcIgBMtEeyD6LYpCyY8Nw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-bZMYBMuEeyD6LYpCyY8Nw"/>
        <condition xmi:type="expression:Expression" xmi:id="_-bZMYRMuEeyD6LYpCyY8Nw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_K1ZO8BMvEeyD6LYpCyY8Nw" name="Si" target="_lQDI0BMvEeyD6LYpCyY8Nw" source="_-_3ycBMuEeyD6LYpCyY8Nw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_K1ZO8RMvEeyD6LYpCyY8Nw"/>
        <condition xmi:type="expression:Expression" xmi:id="_K1ZO8hMvEeyD6LYpCyY8Nw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NbGs8BMvEeyD6LYpCyY8Nw" name="No" target="_NbDpoBMvEeyD6LYpCyY8Nw" source="_-_3ycBMuEeyD6LYpCyY8Nw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NbGs8RMvEeyD6LYpCyY8Nw"/>
        <condition xmi:type="expression:Expression" xmi:id="_NbHUABMvEeyD6LYpCyY8Nw" name="newScript()" content="0 == 0" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zdRC8BPTEeyD6LYpCyY8Nw" target="_0CtSUBPTEeyD6LYpCyY8Nw" source="_tQ188BPTEeyD6LYpCyY8Nw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zdRqABPTEeyD6LYpCyY8Nw"/>
        <condition xmi:type="expression:Expression" xmi:id="_zdRqARPTEeyD6LYpCyY8Nw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2uaqoBPTEeyD6LYpCyY8Nw" target="_XL3P0BNEEeysRqMPSB8vQg" source="_0CtSUBPTEeyD6LYpCyY8Nw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2uaqoRPTEeyD6LYpCyY8Nw"/>
        <condition xmi:type="expression:Expression" xmi:id="_2uaqohPTEeyD6LYpCyY8Nw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_x_dUYBdFEeypj_zk8mSC2g" target="_lQDI0BMvEeyD6LYpCyY8Nw" source="_2NHeQBTtEey3K_c3c_D4pg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_x_iM4BdFEeypj_zk8mSC2g"/>
        <condition xmi:type="expression:Expression" xmi:id="_x_iz8BdFEeypj_zk8mSC2g" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_iCLMIB73Eeyh5_OLYVEXkQ" target="_eLcIgBMtEeyD6LYpCyY8Nw" source="_x6qpABMpEeyD6LYpCyY8Nw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_iCO2gB73Eeyh5_OLYVEXkQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_iCO2gR73Eeyh5_OLYVEXkQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0Hp44B75Eeyh5_OLYVEXkQ" target="_0G-jcB75Eeyh5_OLYVEXkQ" source="_NbDpoBMvEeyD6LYpCyY8Nw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0Hqf8B75Eeyh5_OLYVEXkQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0Hqf8R75Eeyh5_OLYVEXkQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1mXSkB75Eeyh5_OLYVEXkQ" target="_eLcIgBMtEeyD6LYpCyY8Nw" source="_0G-jcB75Eeyh5_OLYVEXkQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1mXSkR75Eeyh5_OLYVEXkQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_1mXSkh75Eeyh5_OLYVEXkQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_C7drcB76Eeyh5_OLYVEXkQ" target="_C7aBEB76Eeyh5_OLYVEXkQ" source="_nYTWIBMsEeyD6LYpCyY8Nw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_C7drcR76Eeyh5_OLYVEXkQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_C7drch76Eeyh5_OLYVEXkQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EzbSoB76Eeyh5_OLYVEXkQ" target="_xCblMBW1Eey3K_c3c_D4pg" source="_C7aBEB76Eeyh5_OLYVEXkQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EzbSoR76Eeyh5_OLYVEXkQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_EzbSoh76Eeyh5_OLYVEXkQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_08c9cB76Eeyh5_OLYVEXkQ" target="_tQ188BPTEeyD6LYpCyY8Nw" source="_BgoScBNEEeysRqMPSB8vQg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_08c9cR76Eeyh5_OLYVEXkQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_08c9ch76Eeyh5_OLYVEXkQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3WaecB76Eeyh5_OLYVEXkQ" target="_BgoScBNEEeysRqMPSB8vQg" source="_lQDI0BMvEeyD6LYpCyY8Nw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3WaecR76Eeyh5_OLYVEXkQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_3Waech76Eeyh5_OLYVEXkQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_TYPzihEDEeyrCJnFey_Gig" documentation="Apoderado de la sociedad anónima" name="Apoderado" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_39owsBMsEeyD6LYpCyY8Nw" name="Area de legales"/>
      <actors xmi:type="process:Actor" xmi:id="_maOu4BMtEeyD6LYpCyY8Nw" name="Personal del area de legales"/>
      <actors xmi:type="process:Actor" xmi:id="_dvvZEBMvEeyD6LYpCyY8Nw" name="Colegio de escribanos"/>
      <actors xmi:type="process:Actor" xmi:id="_-yHoUBNEEeysRqMPSB8vQg" name="Area Mesa de Entradas"/>
      <contract xmi:type="process:Contract" xmi:id="_TYPzixEDEeyrCJnFey_Gig"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TYPzjBEDEeyrCJnFey_Gig">
        <name xmi:type="expression:Expression" xmi:id="_TYPzjREDEeyrCJnFey_Gig" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TYPzjhEDEeyrCJnFey_Gig" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TYPzjxEDEeyrCJnFey_Gig">
        <name xmi:type="expression:Expression" xmi:id="_TYPzkBEDEeyrCJnFey_Gig" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TYPzkREDEeyrCJnFey_Gig" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TYPzkhEDEeyrCJnFey_Gig">
        <name xmi:type="expression:Expression" xmi:id="_TYPzkxEDEeyrCJnFey_Gig" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TYPzlBEDEeyrCJnFey_Gig" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TYPzlREDEeyrCJnFey_Gig">
        <name xmi:type="expression:Expression" xmi:id="_TYPzlhEDEeyrCJnFey_Gig" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TYPzlxEDEeyrCJnFey_Gig" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TYPzmBEDEeyrCJnFey_Gig">
        <name xmi:type="expression:Expression" xmi:id="_TYPzmREDEeyrCJnFey_Gig" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TYPzmhEDEeyrCJnFey_Gig" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_TYPzmxEDEeyrCJnFey_Gig" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_TYPznBEDEeyrCJnFey_Gig" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_TYPznREDEeyrCJnFey_Gig" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_TYPznhEDEeyrCJnFey_Gig" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_TYPznxEDEeyrCJnFey_Gig" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_TYPzoBEDEeyrCJnFey_Gig" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_TYPzoREDEeyrCJnFey_Gig" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_TYPzohEDEeyrCJnFey_Gig" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_TYPzoxEDEeyrCJnFey_Gig" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_TYPzpBEDEeyrCJnFey_Gig" type="Process" element="_TYPMYBEDEeyrCJnFey_Gig" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_TYPzpREDEeyrCJnFey_Gig" type="2007" element="_TYPzcBEDEeyrCJnFey_Gig">
      <children xmi:type="notation:DecorationNode" xmi:id="_TYPzphEDEeyrCJnFey_Gig" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_TYPzpxEDEeyrCJnFey_Gig" type="7001">
        <children xmi:type="notation:Node" xmi:id="_TYPzqBEDEeyrCJnFey_Gig" type="3007" element="_TYPzcREDEeyrCJnFey_Gig">
          <children xmi:type="notation:DecorationNode" xmi:id="_TYPzqREDEeyrCJnFey_Gig" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_TYPzqhEDEeyrCJnFey_Gig" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_TYPzqxEDEeyrCJnFey_Gig" type="3005" element="_TYPzdhEDEeyrCJnFey_Gig" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_TYPzrBEDEeyrCJnFey_Gig" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TYPzrREDEeyrCJnFey_Gig" x="175" y="112" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_TYPzrhEDEeyrCJnFey_Gig" type="3002" element="_TYPzchEDEeyrCJnFey_Gig" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_TYPzrxEDEeyrCJnFey_Gig" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_TYPzsBEDEeyrCJnFey_Gig" x="37" y="-48"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TYPzsREDEeyrCJnFey_Gig" x="59" y="127"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0CtSXRPTEeyD6LYpCyY8Nw" type="3005" element="_0CtSUBPTEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0CtSXxPTEeyD6LYpCyY8Nw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0CtSXhPTEeyD6LYpCyY8Nw" x="1256" y="114" width="153" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_XL324BNEEeysRqMPSB8vQg" type="3062" element="_XL3P0BNEEeysRqMPSB8vQg" fontName="Noto Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_XL4d8BNEEeysRqMPSB8vQg" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_XL4d8RNEEeysRqMPSB8vQg" y="11"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XL324RNEEeysRqMPSB8vQg" x="1522" y="137"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_TYPzshEDEeyrCJnFey_Gig"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_TYPzsxEDEeyrCJnFey_Gig" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_TYPztBEDEeyrCJnFey_Gig"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_TYPztREDEeyrCJnFey_Gig"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TYPzthEDEeyrCJnFey_Gig" x="25" y="682" width="2405" height="358"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_wZCJEBMnEeyD6LYpCyY8Nw" type="3007" element="_wX-ZIBMnEeyD6LYpCyY8Nw">
          <children xmi:type="notation:DecorationNode" xmi:id="_wZCwIBMnEeyD6LYpCyY8Nw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_wZCwIRMnEeyD6LYpCyY8Nw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_eLd9sBMtEeyD6LYpCyY8Nw" type="3005" element="_eLcIgBMtEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_eLd9shMtEeyD6LYpCyY8Nw" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_2NR2UBTtEey3K_c3c_D4pg" type="3043" element="_2NHeQBTtEey3K_c3c_D4pg" fontName=".AppleSystemUIFont">
                <children xmi:type="notation:DecorationNode" xmi:id="_2NR2UhTtEey3K_c3c_D4pg" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_2NR2UxTtEey3K_c3c_D4pg" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2NR2URTtEey3K_c3c_D4pg" x="94" y="66"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eLd9sRMtEeyD6LYpCyY8Nw" x="763" y="36" width="148" height="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-_3ydBMuEeyD6LYpCyY8Nw" type="3008" element="_-_3ycBMuEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_-_4ZgBMuEeyD6LYpCyY8Nw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_-_4ZgRMuEeyD6LYpCyY8Nw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-_3ydRMuEeyD6LYpCyY8Nw" x="791" y="148" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NbEQuBMvEeyD6LYpCyY8Nw" type="3027" element="_NbDpoBMvEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_NbE3wBMvEeyD6LYpCyY8Nw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NbEQuRMvEeyD6LYpCyY8Nw" x="353" y="133" width="166" height="83"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_lQDv4BMvEeyD6LYpCyY8Nw" type="3027" element="_lQDI0BMvEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_lQDv4hMvEeyD6LYpCyY8Nw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lQDv4RMvEeyD6LYpCyY8Nw" x="1009" y="110" width="162" height="81"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0Hh9EB75Eeyh5_OLYVEXkQ" type="3017" element="_0G-jcB75Eeyh5_OLYVEXkQ" fontName="Noto Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_0HikIB75Eeyh5_OLYVEXkQ" type="5032">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_0HikIR75Eeyh5_OLYVEXkQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0Hh9ER75Eeyh5_OLYVEXkQ" x="402" y="51"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_wZCJERMnEeyD6LYpCyY8Nw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_wZCJEhMnEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_wZCJExMnEeyD6LYpCyY8Nw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_wZCwIhMnEeyD6LYpCyY8Nw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wZCJFBMnEeyD6LYpCyY8Nw" x="44" y="1040" width="2411" height="328"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_eEspgBM8EeysRqMPSB8vQg" type="3007" element="_eCUD4BM8EeysRqMPSB8vQg">
          <children xmi:type="notation:DecorationNode" xmi:id="_eExiABM8EeysRqMPSB8vQg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_eExiARM8EeysRqMPSB8vQg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_kuvaQxMpEeyD6LYpCyY8Nw" type="3008" element="_kuuzMBMpEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_kuwBUBMpEeyD6LYpCyY8Nw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_kuwBURMpEeyD6LYpCyY8Nw" x="1" y="-64"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kuvaRBMpEeyD6LYpCyY8Nw" x="489" y="290" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_x6rQEBMpEeyD6LYpCyY8Nw" type="3027" element="_x6qpABMpEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_x6r3IBMpEeyD6LYpCyY8Nw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_x6rQERMpEeyD6LYpCyY8Nw" x="661" y="264" width="222" height="111"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_nYT9OBMsEeyD6LYpCyY8Nw" type="3027" element="_nYTWIBMsEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_nYUkQBMsEeyD6LYpCyY8Nw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nYT9ORMsEeyD6LYpCyY8Nw" x="439" y="445" width="205" height="102"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_BgqHoBNEEeysRqMPSB8vQg" type="3005" element="_BgoScBNEEeysRqMPSB8vQg" fontName="Noto Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_BgqHohNEEeysRqMPSB8vQg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BgqHoRNEEeysRqMPSB8vQg" x="1009" y="540" width="178" height="89"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_tQ2kABPTEeyD6LYpCyY8Nw" type="3027" element="_tQ188BPTEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_tQ2kAhPTEeyD6LYpCyY8Nw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tQ2kARPTEeyD6LYpCyY8Nw" x="1015" y="290" width="167" height="83"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xCcMRRW1Eey3K_c3c_D4pg" type="3005" element="_xCblMBW1Eey3K_c3c_D4pg" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_xCczUBW1Eey3K_c3c_D4pg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xCcMRhW1Eey3K_c3c_D4pg" x="169" y="276" width="162" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_C7bPMB76Eeyh5_OLYVEXkQ" type="3017" element="_C7aBEB76Eeyh5_OLYVEXkQ" fontName="Noto Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_C7bPMh76Eeyh5_OLYVEXkQ" type="5032">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_C7bPMx76Eeyh5_OLYVEXkQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_C7bPMR76Eeyh5_OLYVEXkQ" x="578" y="582"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_eEspgRM8EeysRqMPSB8vQg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_eEspghM8EeysRqMPSB8vQg" fontName="Noto Sans"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_eEspgxM8EeysRqMPSB8vQg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_eExiAhM8EeysRqMPSB8vQg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eEsphBM8EeysRqMPSB8vQg" x="44" y="10" width="2411" height="717"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_TYPztxEDEeyrCJnFey_Gig"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_TYPzuBEDEeyrCJnFey_Gig" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_TYPzuREDEeyrCJnFey_Gig"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_TYPzuhEDEeyrCJnFey_Gig"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TYPzuxEDEeyrCJnFey_Gig" width="2430" height="306"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_TYPzvBEDEeyrCJnFey_Gig"/>
    <edges xmi:type="notation:Connector" xmi:id="_TYPzvREDEeyrCJnFey_Gig" type="4001" element="_TYPzhxEDEeyrCJnFey_Gig" source="_TYPzrhEDEeyrCJnFey_Gig" target="_TYPzqxEDEeyrCJnFey_Gig" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_TYPzvhEDEeyrCJnFey_Gig" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_TYPzvxEDEeyrCJnFey_Gig" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_TYPzwBEDEeyrCJnFey_Gig" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_TYPzwREDEeyrCJnFey_Gig" points="[14, -1, -181, 2]$[125, -1, -70, 2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_LE8VkBMpEeyD6LYpCyY8Nw" type="4001" element="_LE6gYBMpEeyD6LYpCyY8Nw" source="_TYPzqxEDEeyrCJnFey_Gig" target="_xCcMRRW1Eey3K_c3c_D4pg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_LE8VkxMpEeyD6LYpCyY8Nw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_LE8VlBMpEeyD6LYpCyY8Nw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_LE8VkRMpEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_LE8VkhMpEeyD6LYpCyY8Nw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_iYCBkRMpEeyD6LYpCyY8Nw" type="4001" element="_iYBagBMpEeyD6LYpCyY8Nw" source="_xCcMRRW1Eey3K_c3c_D4pg" target="_kuvaQxMpEeyD6LYpCyY8Nw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_iYCBlBMpEeyD6LYpCyY8Nw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iYCBlRMpEeyD6LYpCyY8Nw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_iYCBkhMpEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_iYCBkxMpEeyD6LYpCyY8Nw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xV7kQBMpEeyD6LYpCyY8Nw" type="4001" element="_xV3S0BMpEeyD6LYpCyY8Nw" source="_kuvaQxMpEeyD6LYpCyY8Nw" target="_nYT9OBMsEeyD6LYpCyY8Nw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xV7kQxMpEeyD6LYpCyY8Nw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xV7kRBMpEeyD6LYpCyY8Nw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xV7kQRMpEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xV7kQhMpEeyD6LYpCyY8Nw" points="[0, 22, -11, -139]$[0, 121, -11, -40]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_x67uwBMpEeyD6LYpCyY8Nw" type="4001" element="_x6tsUBMpEeyD6LYpCyY8Nw" source="_kuvaQxMpEeyD6LYpCyY8Nw" target="_x6rQEBMpEeyD6LYpCyY8Nw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_x67uwxMpEeyD6LYpCyY8Nw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_x67uxBMpEeyD6LYpCyY8Nw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_x67uwRMpEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_x67uwhMpEeyD6LYpCyY8Nw" points="[4, -1, -298, 10]$[300, -1, -2, 10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wCfr0BM8EeysRqMPSB8vQg" id="(0.9069767441860465,0.5116279069767442)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_F9dR0BM-EeysRqMPSB8vQg" id="(0.013333333333333334,0.49333333333333335)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-bZMYhMuEeyD6LYpCyY8Nw" type="4001" element="_-bYlUBMuEeyD6LYpCyY8Nw" source="_eLd9sBMtEeyD6LYpCyY8Nw" target="_-_3ydBMuEeyD6LYpCyY8Nw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-bZzcBMuEeyD6LYpCyY8Nw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-bZzcRMuEeyD6LYpCyY8Nw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-bZMYxMuEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-bZMZBMuEeyD6LYpCyY8Nw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_K1Z2ABMvEeyD6LYpCyY8Nw" type="4001" element="_K1ZO8BMvEeyD6LYpCyY8Nw" source="_-_3ydBMuEeyD6LYpCyY8Nw" target="_lQDv4BMvEeyD6LYpCyY8Nw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_K1Z2AxMvEeyD6LYpCyY8Nw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_K1Z2BBMvEeyD6LYpCyY8Nw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_K1Z2ARMvEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_K1Z2AhMvEeyD6LYpCyY8Nw" points="[-3, -2, -444, 118]$[405, -2, -36, 118]$[405, -95, -36, 25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_K1brMBMvEeyD6LYpCyY8Nw" id="(1.0,0.4883720930232558)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GQRG0BW0Eey3K_c3c_D4pg" id="(0.6416666666666667,0.9666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NbK-YBMvEeyD6LYpCyY8Nw" type="4001" element="_NbGs8BMvEeyD6LYpCyY8Nw" source="_-_3ydBMuEeyD6LYpCyY8Nw" target="_NbEQuBMvEeyD6LYpCyY8Nw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NbK-YxMvEeyD6LYpCyY8Nw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NbK-ZBMvEeyD6LYpCyY8Nw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NbK-YRMvEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NbK-YhMvEeyD6LYpCyY8Nw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zdRqAhPTEeyD6LYpCyY8Nw" type="4001" element="_zdRC8BPTEeyD6LYpCyY8Nw" source="_tQ2kABPTEeyD6LYpCyY8Nw" target="_0CtSXRPTEeyD6LYpCyY8Nw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zdRqBRPTEeyD6LYpCyY8Nw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zdRqBhPTEeyD6LYpCyY8Nw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zdRqAxPTEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zdRqBBPTEeyD6LYpCyY8Nw" points="[70, 0, -410, -494]$[449, 0, -31, -494]$[449, 465, -31, -29]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2ubRsBPTEeyD6LYpCyY8Nw" type="4001" element="_2uaqoBPTEeyD6LYpCyY8Nw" source="_0CtSXRPTEeyD6LYpCyY8Nw" target="_XL324BNEEeysRqMPSB8vQg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2ubRsxPTEeyD6LYpCyY8Nw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2ubRtBPTEeyD6LYpCyY8Nw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2ubRsRPTEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2ubRshPTEeyD6LYpCyY8Nw" points="[3, -2, -174, 9]$[164, -2, -13, 9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2ub4wBPTEeyD6LYpCyY8Nw" id="(0.9747899159663865,0.4576271186440678)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2ub4wRPTEeyD6LYpCyY8Nw" id="(0.43333333333333335,0.16666666666666666)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_x_r94BdFEeypj_zk8mSC2g" type="4001" element="_x_dUYBdFEeypj_zk8mSC2g" source="_2NR2UBTtEey3K_c3c_D4pg" target="_lQDv4BMvEeyD6LYpCyY8Nw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_x_sk8BdFEeypj_zk8mSC2g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_x_sk8RdFEeypj_zk8mSC2g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_x_r94RdFEeypj_zk8mSC2g" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_x_r94hdFEeypj_zk8mSC2g" points="[0, 0, -503, -96]$[504, 76, 1, -20]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_x_uaIRdFEeypj_zk8mSC2g" id="(0.4567901234567901,0.19753086419753085)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_iCRSwB73Eeyh5_OLYVEXkQ" type="4001" element="_iCLMIB73Eeyh5_OLYVEXkQ" source="_x6rQEBMpEeyD6LYpCyY8Nw" target="_eLd9sBMtEeyD6LYpCyY8Nw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_iCR50B73Eeyh5_OLYVEXkQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iCR50R73Eeyh5_OLYVEXkQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_iCRSwR73Eeyh5_OLYVEXkQ" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_iCRSwh73Eeyh5_OLYVEXkQ" points="[-20, 62, 177, -558]$[-189, 614, 8, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_iCUWEB73Eeyh5_OLYVEXkQ" id="(1.0,0.25225225225225223)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_iCUWER73Eeyh5_OLYVEXkQ" id="(0.76,0.14)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0Hqf8h75Eeyh5_OLYVEXkQ" type="4001" element="_0Hp44B75Eeyh5_OLYVEXkQ" source="_NbEQuBMvEeyD6LYpCyY8Nw" target="_0Hh9EB75Eeyh5_OLYVEXkQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0HrHAB75Eeyh5_OLYVEXkQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0HrHAR75Eeyh5_OLYVEXkQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0Hqf8x75Eeyh5_OLYVEXkQ" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0Hqf9B75Eeyh5_OLYVEXkQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1mXSkx75Eeyh5_OLYVEXkQ" type="4001" element="_1mXSkB75Eeyh5_OLYVEXkQ" source="_0Hh9EB75Eeyh5_OLYVEXkQ" target="_eLd9sBMtEeyD6LYpCyY8Nw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1mX5oB75Eeyh5_OLYVEXkQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1mX5oR75Eeyh5_OLYVEXkQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1mXSlB75Eeyh5_OLYVEXkQ" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1mXSlR75Eeyh5_OLYVEXkQ" points="[-1, -12, -256, 29]$[256, -54, 1, -13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1mZHwB75Eeyh5_OLYVEXkQ" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1mZHwR75Eeyh5_OLYVEXkQ" id="(0.08,0.34)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_C7eSgB76Eeyh5_OLYVEXkQ" type="4001" element="_C7drcB76Eeyh5_OLYVEXkQ" source="_nYT9OBMsEeyD6LYpCyY8Nw" target="_C7bPMB76Eeyh5_OLYVEXkQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_C7eSgx76Eeyh5_OLYVEXkQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_C7eShB76Eeyh5_OLYVEXkQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_C7eSgR76Eeyh5_OLYVEXkQ" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_C7eSgh76Eeyh5_OLYVEXkQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Ezb5sB76Eeyh5_OLYVEXkQ" type="4001" element="_EzbSoB76Eeyh5_OLYVEXkQ" source="_C7bPMB76Eeyh5_OLYVEXkQ" target="_xCcMRRW1Eey3K_c3c_D4pg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ezb5sx76Eeyh5_OLYVEXkQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Ezb5tB76Eeyh5_OLYVEXkQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Ezb5sR76Eeyh5_OLYVEXkQ" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Ezb5sh76Eeyh5_OLYVEXkQ" points="[-22, -18, 222, 184]$[-230, -192, 14, 10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EzdH0B76Eeyh5_OLYVEXkQ" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EzdH0R76Eeyh5_OLYVEXkQ" id="(0.7037037037037037,0.825)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_08dkgB76Eeyh5_OLYVEXkQ" type="4001" element="_08c9cB76Eeyh5_OLYVEXkQ" source="_BgqHoBNEEeysRqMPSB8vQg" target="_tQ2kABPTEeyD6LYpCyY8Nw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_08dkgx76Eeyh5_OLYVEXkQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_08dkhB76Eeyh5_OLYVEXkQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_08dkgR76Eeyh5_OLYVEXkQ" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_08dkgh76Eeyh5_OLYVEXkQ" points="[0, 0, -16, 214]$[13, -183, -3, 31]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_08fZsB76Eeyh5_OLYVEXkQ" id="(0.5168539325842697,0.033707865168539325)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3WbFgB76Eeyh5_OLYVEXkQ" type="4001" element="_3WaecB76Eeyh5_OLYVEXkQ" source="_lQDv4BMvEeyD6LYpCyY8Nw" target="_BgqHoBNEEeysRqMPSB8vQg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3WbFgx76Eeyh5_OLYVEXkQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3WbFhB76Eeyh5_OLYVEXkQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3WbFgR76Eeyh5_OLYVEXkQ" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3WbFgh76Eeyh5_OLYVEXkQ" points="[-56, -23, -71, 457]$[10, -447, -5, 33]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_3WcToB76Eeyh5_OLYVEXkQ" id="(0.48148148148148145,0.16049382716049382)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
