<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xmlns:transitions="http://www.bonitasoft.org/ns/studio/process/decision/transitions" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision http://www.bonitasoft.org/ns/studio/process/decision/transitions http://www.bonitasoft.org/ns/studio/process#//decision/transitions">
  <process:MainProcess xmi:id="_TYPMYBEDEeyrCJnFey_Gig" name="Diagrama_CreacionDeSociedadesAnonimas" author="monofri" bonitaVersion="7.12.1" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_TYPzcBEDEeyrCJnFey_Gig" name="Creación de sociedades anónimas" displayName="Creación de sociedades anónimas">
      <elements xmi:type="process:Lane" xmi:id="_eCUD4BM8EeysRqMPSB8vQg" name="Mesa de Entradas" actor="_-yHoUBNEEeysRqMPSB8vQg">
        <elements xmi:type="process:XORGateway" xmi:id="_kuuzMBMpEeyD6LYpCyY8Nw" documentation="Determina si la información ingresada por el apoderado en el registro de sociedad anónima es valida" name="¿La infomación es válida?" outgoing="_xV3S0BMpEeyD6LYpCyY8Nw _x6tsUBMpEeyD6LYpCyY8Nw" incoming="_iYBagBMpEeyD6LYpCyY8Nw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_iX3pghMpEeyD6LYpCyY8Nw" name="¿La infomación es válida?" content="¿La infomación es válida?" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_iX3pgRMpEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_iX3pgxMpEeyD6LYpCyY8Nw" name="Determina si la información ingresada por el apoderado en el registro de sociedad anónima es valida" content="Determina si la información ingresada por el apoderado en el registro de sociedad anónima es valida" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_x6qpABMpEeyD6LYpCyY8Nw" name="Generar número de expediente" outgoing="_jKd38BPVEeyD6LYpCyY8Nw" incoming="_x6tsUBMpEeyD6LYpCyY8Nw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_x6qpAhMpEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_x6qpARMpEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_x6qpAxMpEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_x6qpBBMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_x6qpBRMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_x6qpBhMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_x6qpCBMpEeyD6LYpCyY8Nw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_x6qpBxMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_nYTWIBMsEeyD6LYpCyY8Nw" name="Enviar mail al apoderado informando trámite incorrecto y plazo de correción" outgoing="_vtoAUBWzEey3K_c3c_D4pg _5utDsBWzEey3K_c3c_D4pg" incoming="_xV3S0BMpEeyD6LYpCyY8Nw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xVv-ERMpEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xVv-EBMpEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xVv-EhMpEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xVv-ExMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xVv-FBMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xVv-FRMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xVv-FxMpEeyD6LYpCyY8Nw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xVv-FhMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_n4i8cBMsEeyD6LYpCyY8Nw" name="Enviar mail de confirmación al apoderado" outgoing="_KPmKgBNAEeysRqMPSB8vQg" incoming="_jKd38BPVEeyD6LYpCyY8Nw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_wVphERMrEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_wVphEhMrEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_wVphExMrEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_wVphFBMrEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_wVphFRMrEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_wVphFhMrEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_wVphFxMrEeyD6LYpCyY8Nw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_wVphGBMrEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_BgoScBNEEeysRqMPSB8vQg" name="Generar carpeta física" outgoing="_YjkpoBNEEeysRqMPSB8vQg" incoming="_OLqaoBNEEeysRqMPSB8vQg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BgoSchNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BgoScRNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BgoScxNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_BgoSdBNEEeysRqMPSB8vQg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_BgoSdRNEEeysRqMPSB8vQg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_BgoSdhNEEeysRqMPSB8vQg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_BgoSeBNEEeysRqMPSB8vQg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_BgoSdxNEEeysRqMPSB8vQg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Bgo5gRNEEeysRqMPSB8vQg">
            <targetForm xmi:type="expression:Expression" xmi:id="_Bgo5ghNEEeysRqMPSB8vQg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Bgo5gBNEEeysRqMPSB8vQg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Bgo5gxNEEeysRqMPSB8vQg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_H9dzABNEEeysRqMPSB8vQg" name="Generar carpeta digital y enviarla a Google Drive" outgoing="_ZGcGIBNEEeysRqMPSB8vQg" incoming="_OplswBNEEeysRqMPSB8vQg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_H9eaERNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_H9eaEBNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_H9eaEhNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_H9eaExNEEeysRqMPSB8vQg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_H9eaFBNEEeysRqMPSB8vQg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_H9eaFRNEEeysRqMPSB8vQg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_H9eaFxNEEeysRqMPSB8vQg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_H9eaFhNEEeysRqMPSB8vQg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_WeiPwBNEEeysRqMPSB8vQg" name="Espera finalización de carpetas" outgoing="_tQ5AQBPTEeyD6LYpCyY8Nw" incoming="_YjkpoBNEEeysRqMPSB8vQg _ZGcGIBNEEeysRqMPSB8vQg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Wei20RNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Wei20BNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Wei20hNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_tQ188BPTEeyD6LYpCyY8Nw" name="Enviar mail al apoderado informando trámite finalizado" outgoing="_zdRC8BPTEeyD6LYpCyY8Nw" incoming="_tQ5AQBPTEeyD6LYpCyY8Nw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_tQ188hPTEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_tQ188RPTEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_tQ188xPTEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_tQ189BPTEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_tQ189RPTEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_tQ189hPTEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_tQ18-BPTEeyD6LYpCyY8Nw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_tQ189xPTEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_0pe2UBWzEey3K_c3c_D4pg" name="Fin por plazo vencido" incoming="_5utDsBWzEey3K_c3c_D4pg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0ph5oRWzEey3K_c3c_D4pg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0ph5oBWzEey3K_c3c_D4pg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0ph5ohWzEey3K_c3c_D4pg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_xCblMBW1Eey3K_c3c_D4pg" name="Validar información ingresada" outgoing="_iYBagBMpEeyD6LYpCyY8Nw" incoming="_LE6gYBMpEeyD6LYpCyY8Nw _xTmfoBWzEey3K_c3c_D4pg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_LEqBsBMpEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_LEpaoBMpEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_LEqBsRMpEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_LEqBshMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_LEqBsxMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_LEqBtBMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_LEqBthMpEeyD6LYpCyY8Nw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_LEqBtRMpEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_xCcMQhW1Eey3K_c3c_D4pg">
            <targetForm xmi:type="expression:Expression" xmi:id="_xCcMQxW1Eey3K_c3c_D4pg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_xCcMQRW1Eey3K_c3c_D4pg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_xCcMRBW1Eey3K_c3c_D4pg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_TYPzcREDEeyrCJnFey_Gig" documentation="Apoderado de la sociedad anónima" name="Apoderado" actor="_TYPzihEDEeyrCJnFey_Gig">
        <elements xmi:type="process:StartEvent" xmi:id="_TYPzchEDEeyrCJnFey_Gig" name="Registro de sociedad anónima" outgoing="_TYPzhxEDEeyrCJnFey_Gig">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TYPzcxEDEeyrCJnFey_Gig" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TYPzdBEDEeyrCJnFey_Gig" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TYPzdREDEeyrCJnFey_Gig" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_TYPzdhEDEeyrCJnFey_Gig" name="Registrar información de sociedad anónima" outgoing="_LE6gYBMpEeyD6LYpCyY8Nw" incoming="_TYPzhxEDEeyrCJnFey_Gig" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TYPzdxEDEeyrCJnFey_Gig" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TYPzeBEDEeyrCJnFey_Gig" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TYPzeREDEeyrCJnFey_Gig" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_TYPzehEDEeyrCJnFey_Gig" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_TYPzexEDEeyrCJnFey_Gig" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_TYPzfBEDEeyrCJnFey_Gig" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_TYPzfREDEeyrCJnFey_Gig" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_TYPzfhEDEeyrCJnFey_Gig" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_TYPzfxEDEeyrCJnFey_Gig">
            <targetForm xmi:type="expression:Expression" xmi:id="_TYPzgBEDEeyrCJnFey_Gig" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_TYPzgREDEeyrCJnFey_Gig"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_TYPzghEDEeyrCJnFey_Gig" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_0CtSUBPTEeyD6LYpCyY8Nw" name="Retiro de documentación" outgoing="_2uaqoBPTEeyD6LYpCyY8Nw" incoming="_zdRC8BPTEeyD6LYpCyY8Nw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_zdP00BPTEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_zdPNwRPTEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_zdP00RPTEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_zdP00hPTEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_zdP00xPTEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_zdP01BPTEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_zdP01hPTEeyD6LYpCyY8Nw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_zdP01RPTEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_0CtSWhPTEeyD6LYpCyY8Nw">
            <targetForm xmi:type="expression:Expression" xmi:id="_0CtSWxPTEeyD6LYpCyY8Nw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_0CtSWRPTEeyD6LYpCyY8Nw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_0CtSXBPTEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_XL3P0BNEEeysRqMPSB8vQg" name="Fin trámite" incoming="_2uaqoBPTEeyD6LYpCyY8Nw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XL3P0hNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XL3P0RNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XL3P0xNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="__NbxkBTUEeyuXrLeC2z20g" name="Realizar correcciones en el estatuto" outgoing="_EEXEQBTVEeyuXrLeC2z20g" incoming="_DJILEBTVEeyuXrLeC2z20g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="__NifQRTUEeyuXrLeC2z20g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="__NifQBTUEeyuXrLeC2z20g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="__NifQhTUEeyuXrLeC2z20g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="__NifQxTUEeyuXrLeC2z20g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="__NifRBTUEeyuXrLeC2z20g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="__NifRRTUEeyuXrLeC2z20g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="__NifRxTUEeyuXrLeC2z20g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="__NifRhTUEeyuXrLeC2z20g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="__NjGURTUEeyuXrLeC2z20g">
            <targetForm xmi:type="expression:Expression" xmi:id="__NjGUhTUEeyuXrLeC2z20g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="__NjGUBTUEeyuXrLeC2z20g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="__NjGUxTUEeyuXrLeC2z20g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_rV3V4BWzEey3K_c3c_D4pg" name="Realizar correcciones en el registro" outgoing="_xTmfoBWzEey3K_c3c_D4pg" incoming="_vtoAUBWzEey3K_c3c_D4pg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rV3V4RWzEey3K_c3c_D4pg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rV3V4hWzEey3K_c3c_D4pg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rV3V4xWzEey3K_c3c_D4pg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_rV3V5BWzEey3K_c3c_D4pg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_rV3V5RWzEey3K_c3c_D4pg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_rV3V5hWzEey3K_c3c_D4pg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_rV3V5xWzEey3K_c3c_D4pg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_rV3V6BWzEey3K_c3c_D4pg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_rV3V6RWzEey3K_c3c_D4pg">
            <targetForm xmi:type="expression:Expression" xmi:id="_rV3V6hWzEey3K_c3c_D4pg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_rV3V6xWzEey3K_c3c_D4pg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_rV3V7BWzEey3K_c3c_D4pg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <filters xmi:type="process:ActorFilter" xmi:id="_FI200BMtEeyD6LYpCyY8Nw" name="Apoderado" definitionId="bonita-actorfilter-initiator" definitionVersion="1.0">
          <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_FI200RMtEeyD6LYpCyY8Nw" definitionId="bonita-actorfilter-initiator" version="1.0">
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_FI200hMtEeyD6LYpCyY8Nw" key="autoAssign">
              <expression xmi:type="expression:Expression" xmi:id="_FI200xMtEeyD6LYpCyY8Nw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </parameters>
          </configuration>
        </filters>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_wX-ZIBMnEeyD6LYpCyY8Nw" name="Area de legales" actor="_maOu4BMtEeyD6LYpCyY8Nw">
        <elements xmi:type="process:Task" xmi:id="_eLcIgBMtEeyD6LYpCyY8Nw" name="Evaluar estatuto" outgoing="_-bYlUBMuEeyD6LYpCyY8Nw" incoming="_KPmKgBNAEeysRqMPSB8vQg _EEXEQBTVEeyuXrLeC2z20g" actor="_maOu4BMtEeyD6LYpCyY8Nw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dSgVYRMtEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dSgVYBMtEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dSgVYhMtEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dSgVYxMtEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dSgVZBMtEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dSgVZRMtEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dSgVZxMtEeyD6LYpCyY8Nw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dSgVZhMtEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_2NHeQBTtEey3K_c3c_D4pg" name="7 días"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_eLdWoRMtEeyD6LYpCyY8Nw">
            <targetForm xmi:type="expression:Expression" xmi:id="_eLdWohMtEeyD6LYpCyY8Nw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_eLdWoBMtEeyD6LYpCyY8Nw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_eLdWoxMtEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_-_3ycBMuEeyD6LYpCyY8Nw" name="¿Trámite válido?" outgoing="_K1ZO8BMvEeyD6LYpCyY8Nw _NbGs8BMvEeyD6LYpCyY8Nw" incoming="_-bYlUBMuEeyD6LYpCyY8Nw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-bU68RMuEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-bU68BMuEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-bU68hMuEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_NbDpoBMvEeyD6LYpCyY8Nw" name="Enviar email de trámite inválido al apoderado" outgoing="_DJILEBTVEeyuXrLeC2z20g" incoming="_NbGs8BMvEeyD6LYpCyY8Nw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_NbEQsRMvEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_NbEQsBMvEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_NbEQshMvEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_NbEQsxMvEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_NbEQtBMvEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_NbEQtRMvEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_NbEQtxMvEeyD6LYpCyY8Nw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_NbEQthMvEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_lQDI0BMvEeyD6LYpCyY8Nw" name="Realizar estampillado con servicio web" outgoing="_goVKQBNEEeysRqMPSB8vQg" incoming="_K1ZO8BMvEeyD6LYpCyY8Nw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_lQDI0hMvEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_lQDI0RMvEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_lQDI0xMvEeyD6LYpCyY8Nw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_lQDI1BMvEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_lQDI1RMvEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_lQDI1hMvEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_lQDI2BMvEeyD6LYpCyY8Nw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_lQDI1xMvEeyD6LYpCyY8Nw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_goSG8BNEEeysRqMPSB8vQg" name="Generar QR" outgoing="_ifC0QBNEEeysRqMPSB8vQg" incoming="_goVKQBNEEeysRqMPSB8vQg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_goSG8hNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_goSG8RNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_goSG8xNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_goSG9BNEEeysRqMPSB8vQg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_goSG9RNEEeysRqMPSB8vQg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_goSG9hNEEeysRqMPSB8vQg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_goSG-BNEEeysRqMPSB8vQg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_goSG9xNEEeysRqMPSB8vQg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_K1d64BNEEeysRqMPSB8vQg" name="A generar carpetas" outgoing="_OLqaoBNEEeysRqMPSB8vQg _OplswBNEEeysRqMPSB8vQg" incoming="_ifC0QBNEEeysRqMPSB8vQg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_K1d64hNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_K1d64RNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_K1d64xNEEeysRqMPSB8vQg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_TYPzgxEDEeyrCJnFey_Gig">
        <targetForm xmi:type="expression:Expression" xmi:id="_TYPzhBEDEeyrCJnFey_Gig" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_TYPzhREDEeyrCJnFey_Gig">
        <targetForm xmi:type="expression:Expression" xmi:id="_TYPzhhEDEeyrCJnFey_Gig" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_TYPzhxEDEeyrCJnFey_Gig" target="_TYPzdhEDEeyrCJnFey_Gig" source="_TYPzchEDEeyrCJnFey_Gig">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_TYPziBEDEeyrCJnFey_Gig"/>
        <condition xmi:type="expression:Expression" xmi:id="_TYPziREDEeyrCJnFey_Gig" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_LE6gYBMpEeyD6LYpCyY8Nw" target="_xCblMBW1Eey3K_c3c_D4pg" source="_TYPzdhEDEeyrCJnFey_Gig">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_LE7HcBMpEeyD6LYpCyY8Nw"/>
        <condition xmi:type="expression:Expression" xmi:id="_LE7HcRMpEeyD6LYpCyY8Nw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_iYBagBMpEeyD6LYpCyY8Nw" target="_kuuzMBMpEeyD6LYpCyY8Nw" source="_xCblMBW1Eey3K_c3c_D4pg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_iYBagRMpEeyD6LYpCyY8Nw"/>
        <condition xmi:type="expression:Expression" xmi:id="_iYCBkBMpEeyD6LYpCyY8Nw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xV3S0BMpEeyD6LYpCyY8Nw" name="No" target="_nYTWIBMsEeyD6LYpCyY8Nw" source="_kuuzMBMpEeyD6LYpCyY8Nw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_W7VfUBMqEeyD6LYpCyY8Nw">
          <defaultAction xmi:type="transitions:TakeTransitionAction" xmi:id="_W7WGYBMqEeyD6LYpCyY8Nw"/>
        </decisionTable>
        <condition xmi:type="expression:Expression" xmi:id="_xV5IARMpEeyD6LYpCyY8Nw" name="0 == 0" content="0 == 0" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_x6tsUBMpEeyD6LYpCyY8Nw" name="Si" target="_x6qpABMpEeyD6LYpCyY8Nw" source="_kuuzMBMpEeyD6LYpCyY8Nw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_x6u6cBMpEeyD6LYpCyY8Nw"/>
        <condition xmi:type="expression:Expression" xmi:id="_x6u6cRMpEeyD6LYpCyY8Nw" name="0 == 1" content="0 == 1" interpreter="GROOVY" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-bYlUBMuEeyD6LYpCyY8Nw" target="_-_3ycBMuEeyD6LYpCyY8Nw" source="_eLcIgBMtEeyD6LYpCyY8Nw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-bZMYBMuEeyD6LYpCyY8Nw"/>
        <condition xmi:type="expression:Expression" xmi:id="_-bZMYRMuEeyD6LYpCyY8Nw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_K1ZO8BMvEeyD6LYpCyY8Nw" name="Si" target="_lQDI0BMvEeyD6LYpCyY8Nw" source="_-_3ycBMuEeyD6LYpCyY8Nw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_K1ZO8RMvEeyD6LYpCyY8Nw"/>
        <condition xmi:type="expression:Expression" xmi:id="_K1ZO8hMvEeyD6LYpCyY8Nw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NbGs8BMvEeyD6LYpCyY8Nw" name="No" target="_NbDpoBMvEeyD6LYpCyY8Nw" source="_-_3ycBMuEeyD6LYpCyY8Nw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NbGs8RMvEeyD6LYpCyY8Nw"/>
        <condition xmi:type="expression:Expression" xmi:id="_NbHUABMvEeyD6LYpCyY8Nw" name="newScript()" content="0 == 0" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KPmKgBNAEeysRqMPSB8vQg" target="_eLcIgBMtEeyD6LYpCyY8Nw" source="_n4i8cBMsEeyD6LYpCyY8Nw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KPmKgRNAEeysRqMPSB8vQg"/>
        <condition xmi:type="expression:Expression" xmi:id="_KPmKghNAEeysRqMPSB8vQg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OLqaoBNEEeysRqMPSB8vQg" target="_BgoScBNEEeysRqMPSB8vQg" source="_K1d64BNEEeysRqMPSB8vQg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OLqaoRNEEeysRqMPSB8vQg"/>
        <condition xmi:type="expression:Expression" xmi:id="_OLqaohNEEeysRqMPSB8vQg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OplswBNEEeysRqMPSB8vQg" target="_H9dzABNEEeysRqMPSB8vQg" source="_K1d64BNEEeysRqMPSB8vQg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OplswRNEEeysRqMPSB8vQg"/>
        <condition xmi:type="expression:Expression" xmi:id="_OplswhNEEeysRqMPSB8vQg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_YjkpoBNEEeysRqMPSB8vQg" target="_WeiPwBNEEeysRqMPSB8vQg" source="_BgoScBNEEeysRqMPSB8vQg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_YjkpoRNEEeysRqMPSB8vQg"/>
        <condition xmi:type="expression:Expression" xmi:id="_YjkpohNEEeysRqMPSB8vQg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZGcGIBNEEeysRqMPSB8vQg" target="_WeiPwBNEEeysRqMPSB8vQg" source="_H9dzABNEEeysRqMPSB8vQg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZGcGIRNEEeysRqMPSB8vQg"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZGcGIhNEEeysRqMPSB8vQg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_goVKQBNEEeysRqMPSB8vQg" target="_goSG8BNEEeysRqMPSB8vQg" source="_lQDI0BMvEeyD6LYpCyY8Nw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_goVKQRNEEeysRqMPSB8vQg"/>
        <condition xmi:type="expression:Expression" xmi:id="_goVKQhNEEeysRqMPSB8vQg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ifC0QBNEEeysRqMPSB8vQg" target="_K1d64BNEEeysRqMPSB8vQg" source="_goSG8BNEEeysRqMPSB8vQg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ifC0QRNEEeysRqMPSB8vQg"/>
        <condition xmi:type="expression:Expression" xmi:id="_ifC0QhNEEeysRqMPSB8vQg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tQ5AQBPTEeyD6LYpCyY8Nw" target="_tQ188BPTEeyD6LYpCyY8Nw" source="_WeiPwBNEEeysRqMPSB8vQg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tQ5nUBPTEeyD6LYpCyY8Nw"/>
        <condition xmi:type="expression:Expression" xmi:id="_tQ5nURPTEeyD6LYpCyY8Nw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zdRC8BPTEeyD6LYpCyY8Nw" target="_0CtSUBPTEeyD6LYpCyY8Nw" source="_tQ188BPTEeyD6LYpCyY8Nw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zdRqABPTEeyD6LYpCyY8Nw"/>
        <condition xmi:type="expression:Expression" xmi:id="_zdRqARPTEeyD6LYpCyY8Nw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2uaqoBPTEeyD6LYpCyY8Nw" target="_XL3P0BNEEeysRqMPSB8vQg" source="_0CtSUBPTEeyD6LYpCyY8Nw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2uaqoRPTEeyD6LYpCyY8Nw"/>
        <condition xmi:type="expression:Expression" xmi:id="_2uaqohPTEeyD6LYpCyY8Nw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jKd38BPVEeyD6LYpCyY8Nw" target="_n4i8cBMsEeyD6LYpCyY8Nw" source="_x6qpABMpEeyD6LYpCyY8Nw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jKd38RPVEeyD6LYpCyY8Nw"/>
        <condition xmi:type="expression:Expression" xmi:id="_jKd38hPVEeyD6LYpCyY8Nw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DJILEBTVEeyuXrLeC2z20g" target="__NbxkBTUEeyuXrLeC2z20g" source="_NbDpoBMvEeyD6LYpCyY8Nw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DJIyIBTVEeyuXrLeC2z20g"/>
        <condition xmi:type="expression:Expression" xmi:id="_DJIyIRTVEeyuXrLeC2z20g" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EEXEQBTVEeyuXrLeC2z20g" target="_eLcIgBMtEeyD6LYpCyY8Nw" source="__NbxkBTUEeyuXrLeC2z20g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EEXEQRTVEeyuXrLeC2z20g"/>
        <condition xmi:type="expression:Expression" xmi:id="_EEXEQhTVEeyuXrLeC2z20g" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vtoAUBWzEey3K_c3c_D4pg" target="_rV3V4BWzEey3K_c3c_D4pg" source="_nYTWIBMsEeyD6LYpCyY8Nw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vtonYBWzEey3K_c3c_D4pg"/>
        <condition xmi:type="expression:Expression" xmi:id="_vtonYRWzEey3K_c3c_D4pg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xTmfoBWzEey3K_c3c_D4pg" target="_xCblMBW1Eey3K_c3c_D4pg" source="_rV3V4BWzEey3K_c3c_D4pg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xTmfoRWzEey3K_c3c_D4pg"/>
        <condition xmi:type="expression:Expression" xmi:id="_xTnGsBWzEey3K_c3c_D4pg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5utDsBWzEey3K_c3c_D4pg" target="_0pe2UBWzEey3K_c3c_D4pg" source="_nYTWIBMsEeyD6LYpCyY8Nw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5utDsRWzEey3K_c3c_D4pg"/>
        <condition xmi:type="expression:Expression" xmi:id="_5utDshWzEey3K_c3c_D4pg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_TYPzihEDEeyrCJnFey_Gig" documentation="Apoderado de la sociedad anónima" name="Apoderado" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_39owsBMsEeyD6LYpCyY8Nw" name="Area de legales"/>
      <actors xmi:type="process:Actor" xmi:id="_maOu4BMtEeyD6LYpCyY8Nw" name="Personal del area de legales"/>
      <actors xmi:type="process:Actor" xmi:id="_dvvZEBMvEeyD6LYpCyY8Nw" name="Colegio de escribanos"/>
      <actors xmi:type="process:Actor" xmi:id="_-yHoUBNEEeysRqMPSB8vQg" name="Area Mesa de Entradas"/>
      <contract xmi:type="process:Contract" xmi:id="_TYPzixEDEeyrCJnFey_Gig"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TYPzjBEDEeyrCJnFey_Gig">
        <name xmi:type="expression:Expression" xmi:id="_TYPzjREDEeyrCJnFey_Gig" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TYPzjhEDEeyrCJnFey_Gig" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TYPzjxEDEeyrCJnFey_Gig">
        <name xmi:type="expression:Expression" xmi:id="_TYPzkBEDEeyrCJnFey_Gig" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TYPzkREDEeyrCJnFey_Gig" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TYPzkhEDEeyrCJnFey_Gig">
        <name xmi:type="expression:Expression" xmi:id="_TYPzkxEDEeyrCJnFey_Gig" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TYPzlBEDEeyrCJnFey_Gig" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TYPzlREDEeyrCJnFey_Gig">
        <name xmi:type="expression:Expression" xmi:id="_TYPzlhEDEeyrCJnFey_Gig" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TYPzlxEDEeyrCJnFey_Gig" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TYPzmBEDEeyrCJnFey_Gig">
        <name xmi:type="expression:Expression" xmi:id="_TYPzmREDEeyrCJnFey_Gig" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TYPzmhEDEeyrCJnFey_Gig" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_TYPzmxEDEeyrCJnFey_Gig" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_TYPznBEDEeyrCJnFey_Gig" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_TYPznREDEeyrCJnFey_Gig" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_TYPznhEDEeyrCJnFey_Gig" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_TYPznxEDEeyrCJnFey_Gig" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_TYPzoBEDEeyrCJnFey_Gig" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_TYPzoREDEeyrCJnFey_Gig" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_TYPzohEDEeyrCJnFey_Gig" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_TYPzoxEDEeyrCJnFey_Gig" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_TYPzpBEDEeyrCJnFey_Gig" type="Process" element="_TYPMYBEDEeyrCJnFey_Gig" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_TYPzpREDEeyrCJnFey_Gig" type="2007" element="_TYPzcBEDEeyrCJnFey_Gig">
      <children xmi:type="notation:DecorationNode" xmi:id="_TYPzphEDEeyrCJnFey_Gig" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_TYPzpxEDEeyrCJnFey_Gig" type="7001">
        <children xmi:type="notation:Node" xmi:id="_TYPzqBEDEeyrCJnFey_Gig" type="3007" element="_TYPzcREDEeyrCJnFey_Gig">
          <children xmi:type="notation:DecorationNode" xmi:id="_TYPzqREDEeyrCJnFey_Gig" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_TYPzqhEDEeyrCJnFey_Gig" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_TYPzqxEDEeyrCJnFey_Gig" type="3005" element="_TYPzdhEDEeyrCJnFey_Gig" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_TYPzrBEDEeyrCJnFey_Gig" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TYPzrREDEeyrCJnFey_Gig" x="175" y="112" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_TYPzrhEDEeyrCJnFey_Gig" type="3002" element="_TYPzchEDEeyrCJnFey_Gig" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_TYPzrxEDEeyrCJnFey_Gig" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_TYPzsBEDEeyrCJnFey_Gig" x="37" y="-48"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TYPzsREDEeyrCJnFey_Gig" x="59" y="51"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0CtSXRPTEeyD6LYpCyY8Nw" type="3005" element="_0CtSUBPTEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0CtSXxPTEeyD6LYpCyY8Nw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0CtSXhPTEeyD6LYpCyY8Nw" x="1883" y="117" width="153" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_XL324BNEEeysRqMPSB8vQg" type="3062" element="_XL3P0BNEEeysRqMPSB8vQg" fontName="Noto Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_XL4d8BNEEeysRqMPSB8vQg" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_XL4d8RNEEeysRqMPSB8vQg" y="11"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XL324RNEEeysRqMPSB8vQg" x="2163" y="140"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__NxIwBTUEeyuXrLeC2z20g" type="3005" element="__NbxkBTUEeyuXrLeC2z20g" fontName="Noto Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="__Nxv0BTUEeyuXrLeC2z20g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__NxIwRTUEeyuXrLeC2z20g" x="341" y="226" width="164" height="82"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_rV388BWzEey3K_c3c_D4pg" type="3005" element="_rV3V4BWzEey3K_c3c_D4pg" fontName="Noto Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_rV388RWzEey3K_c3c_D4pg" type="5005" element="_rV3V4BWzEey3K_c3c_D4pg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rV388hWzEey3K_c3c_D4pg" x="483" y="42" width="164" height="82"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_TYPzshEDEeyrCJnFey_Gig"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_TYPzsxEDEeyrCJnFey_Gig" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_TYPztBEDEeyrCJnFey_Gig"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_TYPztREDEeyrCJnFey_Gig"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TYPzthEDEeyrCJnFey_Gig" x="25" y="682" width="2405" height="358"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_wZCJEBMnEeyD6LYpCyY8Nw" type="3007" element="_wX-ZIBMnEeyD6LYpCyY8Nw">
          <children xmi:type="notation:DecorationNode" xmi:id="_wZCwIBMnEeyD6LYpCyY8Nw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_wZCwIRMnEeyD6LYpCyY8Nw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_eLd9sBMtEeyD6LYpCyY8Nw" type="3005" element="_eLcIgBMtEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_eLd9shMtEeyD6LYpCyY8Nw" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_2NR2UBTtEey3K_c3c_D4pg" type="3043" element="_2NHeQBTtEey3K_c3c_D4pg" fontName=".AppleSystemUIFont">
                <children xmi:type="notation:DecorationNode" xmi:id="_2NR2UhTtEey3K_c3c_D4pg" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_2NR2UxTtEey3K_c3c_D4pg" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2NR2URTtEey3K_c3c_D4pg" x="-17" y="18"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eLd9sRMtEeyD6LYpCyY8Nw" x="763" y="36" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-_3ydBMuEeyD6LYpCyY8Nw" type="3008" element="_-_3ycBMuEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_-_4ZgBMuEeyD6LYpCyY8Nw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_-_4ZgRMuEeyD6LYpCyY8Nw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-_3ydRMuEeyD6LYpCyY8Nw" x="791" y="148" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NbEQuBMvEeyD6LYpCyY8Nw" type="3027" element="_NbDpoBMvEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_NbE3wBMvEeyD6LYpCyY8Nw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NbEQuRMvEeyD6LYpCyY8Nw" x="353" y="133" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_lQDv4BMvEeyD6LYpCyY8Nw" type="3027" element="_lQDI0BMvEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_lQDv4hMvEeyD6LYpCyY8Nw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lQDv4RMvEeyD6LYpCyY8Nw" x="1099" y="140" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_goSuABNEEeysRqMPSB8vQg" type="3027" element="_goSG8BNEEeysRqMPSB8vQg" fontName="Noto Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_goSuAhNEEeysRqMPSB8vQg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_goSuARNEEeysRqMPSB8vQg" x="1413" y="143"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_K1eh8BNEEeysRqMPSB8vQg" type="3009" element="_K1d64BNEEeysRqMPSB8vQg" fontName="Noto Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_K1eh8hNEEeysRqMPSB8vQg" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_K1eh8xNEEeysRqMPSB8vQg" x="63" y="-48"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_K1eh8RNEEeysRqMPSB8vQg" x="1441" y="36"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_wZCJERMnEeyD6LYpCyY8Nw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_wZCJEhMnEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_wZCJExMnEeyD6LYpCyY8Nw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_wZCwIhMnEeyD6LYpCyY8Nw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wZCJFBMnEeyD6LYpCyY8Nw" x="44" y="1040" width="2411" height="328"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_eEspgBM8EeysRqMPSB8vQg" type="3007" element="_eCUD4BM8EeysRqMPSB8vQg">
          <children xmi:type="notation:DecorationNode" xmi:id="_eExiABM8EeysRqMPSB8vQg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_eExiARM8EeysRqMPSB8vQg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_kuvaQxMpEeyD6LYpCyY8Nw" type="3008" element="_kuuzMBMpEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_kuwBUBMpEeyD6LYpCyY8Nw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_kuwBURMpEeyD6LYpCyY8Nw" x="1" y="-64"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kuvaRBMpEeyD6LYpCyY8Nw" x="559" y="290" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_x6rQEBMpEeyD6LYpCyY8Nw" type="3027" element="_x6qpABMpEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_x6r3IBMpEeyD6LYpCyY8Nw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_x6rQERMpEeyD6LYpCyY8Nw" x="898" y="264" width="150" height="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_nYT9OBMsEeyD6LYpCyY8Nw" type="3027" element="_nYTWIBMsEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_nYUkQBMsEeyD6LYpCyY8Nw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nYT9ORMsEeyD6LYpCyY8Nw" x="511" y="432" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_n4i8eRMsEeyD6LYpCyY8Nw" type="3027" element="_n4i8cBMsEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_n4jjgRMsEeyD6LYpCyY8Nw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_n4jjgBMsEeyD6LYpCyY8Nw" x="912" y="474" width="138" height="69"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_BgqHoBNEEeysRqMPSB8vQg" type="3005" element="_BgoScBNEEeysRqMPSB8vQg" fontName="Noto Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_BgqHohNEEeysRqMPSB8vQg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BgqHoRNEEeysRqMPSB8vQg" x="1351" y="530" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_H9fBIBNEEeysRqMPSB8vQg" type="3027" element="_H9dzABNEEeysRqMPSB8vQg" fontName="Noto Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_H9fBIhNEEeysRqMPSB8vQg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_H9fBIRNEEeysRqMPSB8vQg" x="1493" y="530" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_WekE8BNEEeysRqMPSB8vQg" type="3051" element="_WeiPwBNEEeysRqMPSB8vQg" fontName="Noto Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_WekE8hNEEeysRqMPSB8vQg" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_WekE8xNEEeysRqMPSB8vQg" x="-89" y="-22"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WekE8RNEEeysRqMPSB8vQg" x="1449" y="377"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_tQ2kABPTEeyD6LYpCyY8Nw" type="3027" element="_tQ188BPTEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_tQ2kAhPTEeyD6LYpCyY8Nw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tQ2kARPTEeyD6LYpCyY8Nw" x="1393" y="222" width="167" height="83"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0pju0BWzEey3K_c3c_D4pg" type="3062" element="_0pe2UBWzEey3K_c3c_D4pg" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_0pju0hWzEey3K_c3c_D4pg" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_0pju0xWzEey3K_c3c_D4pg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0pju0RWzEey3K_c3c_D4pg" x="717" y="571"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xCcMRRW1Eey3K_c3c_D4pg" type="3005" element="_xCblMBW1Eey3K_c3c_D4pg" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_xCczUBW1Eey3K_c3c_D4pg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xCcMRhW1Eey3K_c3c_D4pg" x="169" y="276" width="151" height="75"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_eEspgRM8EeysRqMPSB8vQg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_eEspghM8EeysRqMPSB8vQg" fontName="Noto Sans"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_eEspgxM8EeysRqMPSB8vQg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_eExiAhM8EeysRqMPSB8vQg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eEsphBM8EeysRqMPSB8vQg" x="44" y="10" width="2411" height="717"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_TYPztxEDEeyrCJnFey_Gig"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_TYPzuBEDEeyrCJnFey_Gig" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_TYPzuREDEeyrCJnFey_Gig"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_TYPzuhEDEeyrCJnFey_Gig"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TYPzuxEDEeyrCJnFey_Gig" width="2430" height="306"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_TYPzvBEDEeyrCJnFey_Gig"/>
    <edges xmi:type="notation:Connector" xmi:id="_TYPzvREDEeyrCJnFey_Gig" type="4001" element="_TYPzhxEDEeyrCJnFey_Gig" source="_TYPzrhEDEeyrCJnFey_Gig" target="_TYPzqxEDEeyrCJnFey_Gig" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_TYPzvhEDEeyrCJnFey_Gig" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_TYPzvxEDEeyrCJnFey_Gig" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_TYPzwBEDEeyrCJnFey_Gig" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_TYPzwREDEeyrCJnFey_Gig" points="[14, -1, -181, 2]$[125, -1, -70, 2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_LE8VkBMpEeyD6LYpCyY8Nw" type="4001" element="_LE6gYBMpEeyD6LYpCyY8Nw" source="_TYPzqxEDEeyrCJnFey_Gig" target="_xCcMRRW1Eey3K_c3c_D4pg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_LE8VkxMpEeyD6LYpCyY8Nw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_LE8VlBMpEeyD6LYpCyY8Nw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_LE8VkRMpEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_LE8VkhMpEeyD6LYpCyY8Nw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_iYCBkRMpEeyD6LYpCyY8Nw" type="4001" element="_iYBagBMpEeyD6LYpCyY8Nw" source="_xCcMRRW1Eey3K_c3c_D4pg" target="_kuvaQxMpEeyD6LYpCyY8Nw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_iYCBlBMpEeyD6LYpCyY8Nw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iYCBlRMpEeyD6LYpCyY8Nw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_iYCBkhMpEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_iYCBkxMpEeyD6LYpCyY8Nw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xV7kQBMpEeyD6LYpCyY8Nw" type="4001" element="_xV3S0BMpEeyD6LYpCyY8Nw" source="_kuvaQxMpEeyD6LYpCyY8Nw" target="_nYT9OBMsEeyD6LYpCyY8Nw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xV7kQxMpEeyD6LYpCyY8Nw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xV7kRBMpEeyD6LYpCyY8Nw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xV7kQRMpEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xV7kQhMpEeyD6LYpCyY8Nw" points="[0, 22, -11, -139]$[0, 121, -11, -40]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_x67uwBMpEeyD6LYpCyY8Nw" type="4001" element="_x6tsUBMpEeyD6LYpCyY8Nw" source="_kuvaQxMpEeyD6LYpCyY8Nw" target="_x6rQEBMpEeyD6LYpCyY8Nw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_x67uwxMpEeyD6LYpCyY8Nw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_x67uxBMpEeyD6LYpCyY8Nw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_x67uwRMpEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_x67uwhMpEeyD6LYpCyY8Nw" points="[4, -1, -298, 10]$[300, -1, -2, 10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wCfr0BM8EeysRqMPSB8vQg" id="(0.9069767441860465,0.5116279069767442)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_F9dR0BM-EeysRqMPSB8vQg" id="(0.013333333333333334,0.49333333333333335)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-bZMYhMuEeyD6LYpCyY8Nw" type="4001" element="_-bYlUBMuEeyD6LYpCyY8Nw" source="_eLd9sBMtEeyD6LYpCyY8Nw" target="_-_3ydBMuEeyD6LYpCyY8Nw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-bZzcBMuEeyD6LYpCyY8Nw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-bZzcRMuEeyD6LYpCyY8Nw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-bZMYxMuEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-bZMZBMuEeyD6LYpCyY8Nw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_K1Z2ABMvEeyD6LYpCyY8Nw" type="4001" element="_K1ZO8BMvEeyD6LYpCyY8Nw" source="_-_3ydBMuEeyD6LYpCyY8Nw" target="_lQDv4BMvEeyD6LYpCyY8Nw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_K1Z2AxMvEeyD6LYpCyY8Nw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_K1Z2BBMvEeyD6LYpCyY8Nw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_K1Z2ARMvEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_K1Z2AhMvEeyD6LYpCyY8Nw" points="[-3, -2, -444, 118]$[405, -2, -36, 118]$[405, -95, -36, 25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_K1brMBMvEeyD6LYpCyY8Nw" id="(1.0,0.4883720930232558)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GQRG0BW0Eey3K_c3c_D4pg" id="(0.6416666666666667,0.9666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NbK-YBMvEeyD6LYpCyY8Nw" type="4001" element="_NbGs8BMvEeyD6LYpCyY8Nw" source="_-_3ydBMuEeyD6LYpCyY8Nw" target="_NbEQuBMvEeyD6LYpCyY8Nw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NbK-YxMvEeyD6LYpCyY8Nw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NbK-ZBMvEeyD6LYpCyY8Nw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NbK-YRMvEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NbK-YhMvEeyD6LYpCyY8Nw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KPmxkBNAEeysRqMPSB8vQg" type="4001" element="_KPmKgBNAEeysRqMPSB8vQg" source="_n4i8eRMsEeyD6LYpCyY8Nw" target="_eLd9sBMtEeyD6LYpCyY8Nw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KPnYoBNAEeysRqMPSB8vQg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KPnYoRNAEeysRqMPSB8vQg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KPmxkRNAEeysRqMPSB8vQg" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KPmxkhNAEeysRqMPSB8vQg" points="[36, 8, 174, -593]$[36, 429, 174, -172]$[-133, 429, 5, -172]$[-133, 576, 5, -25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_KPpN0BNAEeysRqMPSB8vQg" id="(0.2826086956521739,0.8840579710144928)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OLrBsBNEEeysRqMPSB8vQg" type="4001" element="_OLqaoBNEEeysRqMPSB8vQg" source="_K1eh8BNEEeysRqMPSB8vQg" target="_BgqHoBNEEeysRqMPSB8vQg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OLrBsxNEEeysRqMPSB8vQg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OLrBtBNEEeysRqMPSB8vQg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OLrBsRNEEeysRqMPSB8vQg" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OLrBshNEEeysRqMPSB8vQg" points="[-43, -10, 30, 572]$[-77, -10, -4, 572]$[-77, -552, -4, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OLrowBNEEeysRqMPSB8vQg" id="(1.0,0.7209302325581395)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OpmT0BNEEeysRqMPSB8vQg" type="4001" element="_OplswBNEEeysRqMPSB8vQg" source="_K1eh8BNEEeysRqMPSB8vQg" target="_H9fBIBNEEeysRqMPSB8vQg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OpmT0xNEEeysRqMPSB8vQg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OpmT1BNEEeysRqMPSB8vQg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OpmT0RNEEeysRqMPSB8vQg" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OpmT0hNEEeysRqMPSB8vQg" points="[-16, -25, -112, 276]$[93, -271, -3, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Opnh8BNEEeysRqMPSB8vQg" id="(1.0,0.7209302325581395)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_YjlQsBNEEeysRqMPSB8vQg" type="4001" element="_YjkpoBNEEeysRqMPSB8vQg" source="_BgqHoBNEEeysRqMPSB8vQg" target="_WekE8BNEEeysRqMPSB8vQg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_YjlQsxNEEeysRqMPSB8vQg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_YjlQtBNEEeysRqMPSB8vQg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_YjlQsRNEEeysRqMPSB8vQg" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YjlQshNEEeysRqMPSB8vQg" points="[2, -5, -64, 132]$[2, -64, -64, 73]$[66, -64, 0, 73]$[66, -115, 0, 22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Yjl3wBNEEeysRqMPSB8vQg" id="(0.44166666666666665,0.08333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZGcGIxNEEeysRqMPSB8vQg" type="4001" element="_ZGcGIBNEEeysRqMPSB8vQg" source="_H9fBIBNEEeysRqMPSB8vQg" target="_WekE8BNEEeysRqMPSB8vQg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZGctMBNEEeysRqMPSB8vQg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZGctMRNEEeysRqMPSB8vQg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZGcGJBNEEeysRqMPSB8vQg" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZGcGJRNEEeysRqMPSB8vQg" points="[-66, -30, 77, 132]$[-66, -89, 77, 73]$[-143, -89, 0, 73]$[-143, -140, 0, 22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZGdUQBNEEeysRqMPSB8vQg" id="(1.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_goVKQxNEEeysRqMPSB8vQg" type="4001" element="_goVKQBNEEeysRqMPSB8vQg" source="_lQDv4BMvEeyD6LYpCyY8Nw" target="_goSuABNEEeysRqMPSB8vQg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_goVxUBNEEeysRqMPSB8vQg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_goVxURNEEeysRqMPSB8vQg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_goVKRBNEEeysRqMPSB8vQg" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_goVKRRNEEeysRqMPSB8vQg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ifDbUBNEEeysRqMPSB8vQg" type="4001" element="_ifC0QBNEEeysRqMPSB8vQg" source="_goSuABNEEeysRqMPSB8vQg" target="_K1eh8BNEEeysRqMPSB8vQg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ifDbUxNEEeysRqMPSB8vQg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ifDbVBNEEeysRqMPSB8vQg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ifDbURNEEeysRqMPSB8vQg" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ifDbUhNEEeysRqMPSB8vQg" points="[-51, -30, 0, 86]$[-51, -94, 0, 22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ifECYBNEEeysRqMPSB8vQg" id="(1.0,0.6)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tQ5nUhPTEeyD6LYpCyY8Nw" type="4001" element="_tQ5AQBPTEeyD6LYpCyY8Nw" source="_WekE8BNEEeysRqMPSB8vQg" target="_tQ2kABPTEeyD6LYpCyY8Nw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tQ5nVRPTEeyD6LYpCyY8Nw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tQ5nVhPTEeyD6LYpCyY8Nw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tQ5nUxPTEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tQ5nVBPTEeyD6LYpCyY8Nw" points="[0, -21, 8, 121]$[0, -107, 8, 35]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zdRqAhPTEeyD6LYpCyY8Nw" type="4001" element="_zdRC8BPTEeyD6LYpCyY8Nw" source="_tQ2kABPTEeyD6LYpCyY8Nw" target="_0CtSXRPTEeyD6LYpCyY8Nw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zdRqBRPTEeyD6LYpCyY8Nw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zdRqBhPTEeyD6LYpCyY8Nw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zdRqAxPTEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zdRqBBPTEeyD6LYpCyY8Nw" points="[70, 0, -410, -494]$[449, 0, -31, -494]$[449, 465, -31, -29]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2ubRsBPTEeyD6LYpCyY8Nw" type="4001" element="_2uaqoBPTEeyD6LYpCyY8Nw" source="_0CtSXRPTEeyD6LYpCyY8Nw" target="_XL324BNEEeysRqMPSB8vQg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2ubRsxPTEeyD6LYpCyY8Nw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2ubRtBPTEeyD6LYpCyY8Nw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2ubRsRPTEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2ubRshPTEeyD6LYpCyY8Nw" points="[3, -2, -174, 9]$[164, -2, -13, 9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2ub4wBPTEeyD6LYpCyY8Nw" id="(0.9747899159663865,0.4576271186440678)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2ub4wRPTEeyD6LYpCyY8Nw" id="(0.43333333333333335,0.16666666666666666)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jKd38xPVEeyD6LYpCyY8Nw" type="4001" element="_jKd38BPVEeyD6LYpCyY8Nw" source="_x6rQEBMpEeyD6LYpCyY8Nw" target="_n4i8eRMsEeyD6LYpCyY8Nw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jKefABPVEeyD6LYpCyY8Nw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jKefARPVEeyD6LYpCyY8Nw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jKd39BPVEeyD6LYpCyY8Nw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jKd39RPVEeyD6LYpCyY8Nw" points="[-61, 50, 6, -169]$[-61, 185, 6, -34]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jKfGEBPVEeyD6LYpCyY8Nw" id="(1.0,0.3333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DJKAQBTVEeyuXrLeC2z20g" type="4001" element="_DJILEBTVEeyuXrLeC2z20g" source="_NbEQuBMvEeyD6LYpCyY8Nw" target="__NxIwBTUEeyuXrLeC2z20g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DJKnUBTVEeyuXrLeC2z20g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DJKnURTVEeyuXrLeC2z20g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DJKAQRTVEeyuXrLeC2z20g" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DJKAQhTVEeyuXrLeC2z20g" points="[-52, -26, 18, 224]$[-52, -209, 18, 41]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DJNDkBTVEeyuXrLeC2z20g" id="(1.0,0.37681159420289856)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EEXrUBTVEeyuXrLeC2z20g" type="4001" element="_EEXEQBTVEeyuXrLeC2z20g" source="__NxIwBTUEeyuXrLeC2z20g" target="_eLd9sBMtEeyD6LYpCyY8Nw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EEYSYBTVEeyuXrLeC2z20g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EEYSYRTVEeyuXrLeC2z20g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EEXrURTVEeyuXrLeC2z20g" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EEXrUhTVEeyuXrLeC2z20g" points="[0, 0, -141, -213]$[91, 212, -50, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EEaHkBTVEeyuXrLeC2z20g" id="(1.0,0.30097087378640774)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-7nfcBTtEey3K_c3c_D4pg" id="(0.35,0.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vtqckBWzEey3K_c3c_D4pg" type="4001" element="_vtoAUBWzEey3K_c3c_D4pg" source="_nYT9OBMsEeyD6LYpCyY8Nw" target="_rV388BWzEey3K_c3c_D4pg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vtrqsBWzEey3K_c3c_D4pg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vtrqsRWzEey3K_c3c_D4pg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vtqckRWzEey3K_c3c_D4pg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vtqckhWzEey3K_c3c_D4pg" points="[-91, 50, 30, -248]$[-91, 297, 30, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vtuG8BWzEey3K_c3c_D4pg" id="(1.0,0.375)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vtuuABWzEey3K_c3c_D4pg" id="(0.40853658536585363,0.012195121951219513)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xTntwBWzEey3K_c3c_D4pg" type="4001" element="_xTmfoBWzEey3K_c3c_D4pg" source="_rV388BWzEey3K_c3c_D4pg" target="_xCcMRRW1Eey3K_c3c_D4pg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xTntwxWzEey3K_c3c_D4pg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xTntxBWzEey3K_c3c_D4pg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xTntwRWzEey3K_c3c_D4pg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xTntwhWzEey3K_c3c_D4pg" points="[-108, -28, 281, 386]$[-108, -96, 281, 318]$[-377, -96, 12, 318]$[-377, -401, 12, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xTpi8BWzEey3K_c3c_D4pg" id="(1.0,0.34146341463414637)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xTpi8RWzEey3K_c3c_D4pg" id="(0.5894039735099338,0.8266666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5uuR0BWzEey3K_c3c_D4pg" type="4001" element="_5utDsBWzEey3K_c3c_D4pg" source="_nYT9OBMsEeyD6LYpCyY8Nw" target="_0pju0BWzEey3K_c3c_D4pg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5uu44BWzEey3K_c3c_D4pg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5uu44RWzEey3K_c3c_D4pg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5uuR0RWzEey3K_c3c_D4pg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5uuR0hWzEey3K_c3c_D4pg" points="[-75, 48, -124, -64]$[-75, 121, -124, 9]$[46, 121, -3, 9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5uwuEBWzEey3K_c3c_D4pg" id="(1.0,0.4)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5uwuERWzEey3K_c3c_D4pg" id="(0.1,0.16666666666666666)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
